### ISSUE TITLE
Error Failed to download Something to do with lyrics

### ISSUE THREAD

**Issue by rittennig** [glomatico/gamdl#100]
![image](https://github.com/glomatico/gamdl/assets/76802645/d45df3b0-763e-4983-98d4-a632a218687c)

Please check the error. 

Config File
![image](https://github.com/glomatico/gamdl/assets/76802645/654769fe-212d-48c6-abc0-502ac36d9d77)

**Comment by glomatico** [comment]
Fixed on the new version.
