### ISSUE TITLE
.lrc formatting

### ISSUE THREAD

**Issue by twentyonekoalas** [glomatico/gamdl#103]
I mainly use gamdl for lyrics.  The 2.0 release still retrieves lyrics, but it now adds a space between lines which is the incorrect format for .lrc files.  Whatever the previous method used before 2.0 had correct formatting. 

Here's an example of the current formatting (on the left) vs correct formatting (on the right)
![CleanShot 2024-04-12 at 13 58 36@2x](https://github.com/glomatico/gamdl/assets/62671287/0aaeea4b-2c03-402c-b4b9-8b53b16779c8)

**Comment by glomatico** [comment]
Thanks. Fixed on the new version.
