### ISSUE TITLE
Error About idk what happened 

### ISSUE THREAD

**Issue by rittennig** [glomatico/gamdl#104]
![image](https://github.com/glomatico/gamdl/assets/76802645/1d7ed782-85b8-40db-aa33-3ca76ee5c066)

Here is config file:
![image](https://github.com/glomatico/gamdl/assets/76802645/a74d1fd6-8bed-4957-9ba7-e2bce178c301)

**Comment by rittennig** [comment]
I want to use atmos codec but it had similar error just KeyError is different.

**Comment by glomatico** [comment]
https://github.com/glomatico/gamdl/issues/102#issuecomment-2052323892

**Comment by rittennig** [comment]
Hi 
I have checked the song and it is available in atmos codec i guess im not doing something right. aac-legacy and aac-he-legacy works but i want atleast biaural or atmos.
