### ISSUE TITLE
Cannot fetch all playlist songs

### ISSUE THREAD

**Issue by karsandor2022** [glomatico/gamdl#107]
I have a large music library (to be exact there are 727 songs in the list) and when I try to download the music it only detected some of the songs.
I tried to download one of the songs separately and it recognized and downloaded them.

![Képernyőkép 2024-04-22 101608](https://github.com/glomatico/gamdl/assets/116633994/46872f52-b041-4bf7-a805-98c1c444dc86)
![Képernyőkép 2024-04-22 101650](https://github.com/glomatico/gamdl/assets/116633994/f6602242-2e1b-416d-a3b3-9f25fa544a39)
![Képernyőkép 2024-04-22 101811](https://github.com/glomatico/gamdl/assets/116633994/fe37e9e5-58e1-48ee-b518-b7778edae863)

**Comment by glomatico** [comment]
Can you provide the link?

**Comment by karsandor2022** [comment]
This is the list 
https://music.apple.com/hu/playlist/all-music-2-relisted/pl.u-xlyNqrNIkRWVzeG?l=hu

**Comment by karsandor2022** [comment]
> Can you provide the link?

Here it is

https://music.apple.com/hu/playlist/all-music-2-relisted/pl.u-xlyNqrNIkRWVzeG?l=hu

**Comment by karsandor2022** [comment]
> That's an issue with Apple Music API. I can't do much right now.

At least I know that it is a API problem
