### ISSUE TITLE
ModuleNotFoundError: No module named 'pywidevine.L3'

### ISSUE THREAD

**Issue by DarkHorse-APP2** [glomatico/gamdl#11]
spotify_aac_downloader.py", line 11, in <module>
    from pywidevine.L3.cdm.cdm import Cdm
ModuleNotFoundError: No module named 'pywidevine.L3'

**Comment by glomatico** [comment]
This is unrelated with gamdl, but you have to run the script at the same folder where spotify_aac_downloader.py is.
