### ISSUE TITLE
"You sent an invalid link."

### ISSUE THREAD

**Issue by AlexIs387** [glomatico/gamdl#111]
You sent an invalid link.

_Originally posted by @glomatico in https://github.com/glomatico/gamdl/issues/98#issuecomment-2048520363_

And then what is a valid link supposed to contain?

**Comment by glomatico** [comment]
What link did you tried?

**Comment by AlexIs387** [comment]
Well it's opened without problems in my browser and it's not even downloaded. Also I get this error:

I:\programas\Portable Python-3.10.5 x64\App\Python\Scripts>gamdl https://music.apple.com/us/album/yesterday/1441164524?i=1441164805 --print-exceptions
[WARNING  16:01:23] mp4decrypt not found at "mp4decrypt", music videos will not be downloaded
[INFO     16:01:23] (URL 1/1) Checking "https://music.apple.com/us/album/yesterday/1441164524?i=1441164805"
[INFO     16:01:23] (Track 1/1 from URL 1/1) Downloading "Yesterday"
[ERROR    16:01:23] (Track 1/1 from URL 1/1) Failed to download "Yesterday"
Traceback (most recent call last):
  File "I:\programas\Portable Python-3.10.5 x64\App\Python\lib\site-packages\gamdl\apple_music_api.py", line 231, in get_webplayback
    assert webplayback
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\programas\Portable Python-3.10.5 x64\App\Python\lib\site-packages\gamdl\cli.py", line 489, in main
    webplayback = apple_music_api.get_webplayback(track["id"])
  File "I:\programas\Portable Python-3.10.5 x64\App\Python\lib\site-packages\gamdl\apple_music_api.py", line 237, in get_webplayback
    self._raise_response_exception(response)
  File "I:\programas\Portable Python-3.10.5 x64\App\Python\lib\site-packages\gamdl\apple_music_api.py", line 73, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 200: {
"dialog":{"defaultButton":"ok", "message":"No Active Subscription", "m-allowed":false, "explanation":"Make sure you're signed in with the Apple ID that's associated with your Apple Music subscription or resubscribe in account settings. ", "initialCheckboxValue":true, "okButtonString":"OK"}, "customerMessage":"No Active Subscription", "failureType":"3063", "pings":[],
"metrics":{"dialogId":"MZCommerce.FuseNoActiveSubscriptionFailureKey", "eventType":"dialog", "message":"No Active Subscription", "mtTopic":"xp_its_main", "actionUrl":"play.itunes.apple.com/WebObjects/MZPlay.woa/wa/webPlayback?l=en-US", "messageCode":"3063", "options":["OK"]}, "cancel-purchase-batch":true, "m-allowed":false}
[INFO     16:01:23] Done (1 error(s))

You know what? this repo is an absolute time wasting, for users having downloaded it and you having create it.

**Comment by glomatico** [comment]
For those who don't read stuff, yeah
