### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by vijaykrpp** [glomatico/gamdl#113]
I have an active Apple Music subscription, and all the pre-req are installed. But I am getting this error:

![image](https://github.com/glomatico/gamdl/assets/32255903/4186f13e-8aac-4563-b1f3-e0ebce1ef0fb)

**Comment by glomatico** [comment]
You're using an old version of FFmpeg. Use the recommended version from the readme.

**Comment by vijaykrpp** [comment]
Thanks. It worked. But I observed that a few songs are not downloadable, thouugh I can stream them well.

https://music.apple.com/us/album/ddu-du-ddu-du/1551479990?i=1551479993
https://music.apple.com/us/album/very-nice/1130828885?i=1130828898

Error: [{\"id\":\"E72OZKHD4TCFLQ3EBO6HRQDMWY\",\"title\":\"Resource Not Found\",\"detail\":\"Resource with requested id was not found\",\"status\":\"404\",\"code\":\"40400\"}]}"}
