### ISSUE TITLE
Kindly Make This Enhancement

### ISSUE THREAD

**Issue by Rajeshsahoo12** [glomatico/gamdl#115]
Hi Dev,

I am using gamdl 2.2.2 to get my favorite albums from favorite artists. I use this cmd to get it done.

gamdl https://music.apple.com/in/artist/yuvanshankar-raja/117755361 --codec-song aac-legacy

![image](https://github.com/glomatico/gamdl/assets/54216637/5a5e31c1-f47b-49de-a87e-6d1876ea7122)

After selecting albums to download. It lists all albums available. Now it is asking for which album to download.

![image](https://github.com/glomatico/gamdl/assets/54216637/0c669616-14b6-451a-8881-8f00e3f6f71b)

But if user wants all albums to download. Not one by one.

Right after we select albums it sud start downloading all albums. Not asking user input which album to download. 

May add this enhancement by using some custom flag in cli.

Default behaviour sud be kept as current. But if used with flag then it will start downloading all albums after we select what to download.

Thanks

**Comment by glomatico** [comment]
Hit Ctrl+A to select all albums.

**Comment by Rajeshsahoo12** [comment]
Ohhhh didn't knew that. Thanks dev.
