### ISSUE TITLE
failed to remux atmos

### ISSUE THREAD

**Issue by okidokios** [glomatico/gamdl#120]
Hello I tried to download atmos songs but I get this ffmpeg error I downloaded the suggest ffmpeg binarie from the readme but still get it.

`gamdl` "https://music.apple.com/us/album/lovefool/1450141530?i=1450141548" --ffmpeg-path "c:/rclone/ffmpeg.exe"
[WARNING  18:25:33] You have chosen a non-legacy codec. Support for non-legacy codecs are not guaranteed, as most of the songs cannot be downloaded when using non-legacy codecs.
[INFO     18:25:33] (URL 1/1) Checking "https://music.apple.com/us/album/lovefool/1450141530?i=1450141548"
[INFO     18:25:34] (Track 1/1 from URL 1/1) Downloading "Lovefool"
[eac3 @ 0000013912f8b580] invalid sample rate
[eac3 @ 0000013912f8b580] unable to determine channel mode
[aost#0:0/copy @ 00000139130fac00] Error submitting a packet to the muxer: Invalid data found when processing input
    Last message repeated 1 times
[out#0/mp4 @ 0000013912f8b740] Error muxing a packet
[out#0/mp4 @ 0000013912f8b740] Task finished with error code: -1094995529 (Invalid data found when processing input)
[out#0/mp4 @ 0000013912f8b740] Terminating thread with return code -1094995529 (Invalid data found when processing input)
[ERROR    18:25:40] (Track 1/1 from URL 1/1) Failed to download "Lovefool"``

**Comment by glomatico** [comment]
Try using the recommended ffmpeg binary listed on the readme.
