### ISSUE TITLE
What is aac-legacy?

### ISSUE THREAD

**Issue by DwayneHoobler** [glomatico/gamdl#121]
I am confused about the meaning of aac-legacy codec. I could not find a definition anywhere. What is the difference between the aac-legacy codec and the aac codec, and is the quality of the audio the same or does it differ?

**Comment by glomatico** [comment]
Sorry, I should have added an explanation about this on the README.

The main difference between `aac` and `aac-legacy` is the API used to get the stream info.

`aac` uses the amp-api that is used in the app client, while `aac-legacy` uses the webplayback API that is used on the web client.

In terms of quality, they are pretty much the same, but sometimes you can get 48kHz audio using `aac`.
