### ISSUE TITLE
Cookies Help

### ISSUE THREAD

**Issue by LucasLu1215** [glomatico/gamdl#126]
May I know where to put "cookies.txt" in?

**Comment by LucasLu1215** [comment]
I put it in the Lib\site-package\gamdl but it doesn't work...

**Comment by Imgkl** [comment]
No. Put this file under the dir where you are tying. For example, I have this cookies.txt under Downloads DIR. So I navigate to Downloads from my terminal and run the `gamdl` command.

**Comment by LucasLu1215** [comment]
emm...

> No. Put this file under the dir where you are tying. For example, I have this cookies.txt under Downloads DIR. So I navigate to Downloads from my terminal and run the `gamdl` command.

emm...What is the dir where I am tying?

**Comment by Imgkl** [comment]
Where you are trying to download. 

Place the cookies.txt in downloads and on Terminal, `cd Downloads/` and try `gamdl YOUR_SONG_OR_PLAYLIST_URL`

**Comment by Imgkl** [comment]
Alternately you can also pass the cookies.txt file using `--cookies-path` flag

**Comment by LucasLu1215** [comment]
Ohhh
I got it! Thanks very much!
