### ISSUE TITLE
Videos with music-movie in the url fail to download

### ISSUE THREAD

**Issue by welppee** [glomatico/gamdl#128]
Hi links with music-movie in the url like this example -> https://music.apple.com/be/music-movie/the-chromatica-interview/1515447095 fail to download the script is not expecting this type of urls below is the error i'am getting

it seems like the first step to try to solve this issue is would be adding the music-video to the regex then handling it further in _get_download_queue

command used -> gamdl  "https://music.apple.com/be/music-movie/the-chromatica-interview/1515447095" --print-exceptions --log-level DEBUG

[DEBUG    12:37:23] Starting Downloader
[DEBUG    12:37:30] Setting Up CDM
[WARNING  12:37:30] You Have Chosen A non-legacy Codec. Support For non-legacy codecs Are Not Guaranteed, As Most Of The Songs Cannot Be Downloaded When Using non-legacy Codecs.
[INFO     12:37:30] (URL 1/1) Checking "https://music.apple.com/be/music-movie/the-chromatica-interview/1515447095"
[ERROR    12:37:30] (URL 1/1) Failed To Check "https://music.apple.com/be/music-movie/the-chromatica-interview/1515447095"
Traceback (most recent call last):
  File "C:\Users\ee\AppData\Local\Programs\Python\Python39\lib\site-packages\gamdl\cli.py", line 447, in main
    url_info = downloader.get_url_info(url)
  File "C:\Users\ee\AppData\Local\Programs\Python\Python39\lib\site-packages\gamdl\downloader.py", line 132, in get_url_info
    url_info.storefront = url_regex_result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
[INFO     12:37:30] Done (1 Error(s))

**Comment by glomatico** [comment]
Music movies are not supported at the moment.
