### ISSUE TITLE
Failed to check URL with unicode characters

### ISSUE THREAD

**Issue by TachyonicSpeed** [glomatico/gamdl#129]
I am trying to download from this original URL `https://music.apple.com/jp/album/垂直落下/1648876478?i=1648876739&l=en-US`

```
gamdl "https://music.apple.com/jp/album/%E5%9E%82%E7%9B%B4%E8%90%BD%E4%B8%8B/1648876478?i=1648876739&l=en-US"
[WARNING  19:06:20] mp4decrypt not found at "mp4decrypt", music videos will not be downloaded
[INFO     19:06:20] (URL 1/1) Checking "https://music.apple.com/jp/album/%E5%9E%82%E7%9B%B4%E8%90%BD%E4%B8%8B/1648876478?i=1648876739&l=en-US"
[ERROR    19:06:20] (URL 1/1) Failed to check "https://music.apple.com/jp/album/%E5%9E%82%E7%9B%B4%E8%90%BD%E4%B8%8B/1648876478?i=1648876739&l=en-US"
[INFO     19:06:20] Done (1 error(s))
```
Are such urls not supported?

**Comment by glomatico** [comment]
I couldn't reproduce your issue with the link you provided. Make sure you are using the latest version and try using a different a terminal.

**Comment by gingerbeardman** [comment]
How about the equivalent URL https://music.apple.com/jp/album/1648876478

**Comment by vijaykrpp** [comment]
> How about the equivalent URL https://music.apple.com/jp/album/1648876478

Yes, the tool create issues when any special characters are there in the URL.

![image](https://github.com/user-attachments/assets/0381229b-c841-4d04-9a28-1a40b38295ab)

**Comment by gingerbeardman** [comment]
@vijaykrpp i think it's more that the item that is not available in some store regions?

the original Japanese album is not available in my region, only Japan.

but these two download just fine for me, using short or long links:
- https://music.apple.com/gb/album/%E3%81%9F%E3%81%BE%E3%81%AB%E3%81%AF%E3%81%B2%E3%81%A8%E3%82%8A%E3%81%AB%E3%81%95%E3%81%9B%E3%81%A6%E3%82%88%E3%81%AD/1758660886?i=1758661160
- https://music.apple.com/jp/album/1758660886
and
- https://music.apple.com/gb/album/%E5%BC%95%E5%8A%9B%E4%BB%BB%E3%81%9B/1750613723?i=1750613724
or
- https://music.apple.com/jp/album/1750613723
