### ISSUE TITLE
Quality Selection

### ISSUE THREAD

**Issue by DrJapan** [glomatico/gamdl#136]
Hello!

This is more of a question, than an issue, but I was wondering how the quality is selected, for the various media? Is it always the highest possible?

I tried downloading a visual album, and I kept getting an error saying that it couldn't download. I can download the individual tracks. 

What would be the proper syntax, for choosing h265?

Thank you!

**Comment by DrJapan** [comment]
On a similar path, how would I download the Dolby Atmos version of a music video/Audio Album.

Here is the album in question: https://music.apple.com/ca/album/yanni-live-at-the-acropolis-25th-anniversary-edition/1444143446

**Comment by glomatico** [comment]
Closing this issue since I already replied to you.
