### ISSUE TITLE
Why can’t I download lossless audio but the telegram bot can?

### ISSUE THREAD

**Issue by iwlbvk2489** [glomatico/gamdl#138]
The bot is too slow for my use case (downloading >2000 songs), but gamdl fails to download ALAC .m4a files or any other lossless files when I use “ask” instead of “alac”. I already have mp4decrypt, so why doesn’t it work?

I also tried the exact same url with the Glomatico bot and it worked. It was slow, but it still got me the lossless file.

**Comment by glomatico** [comment]
The API returns manifests that don't have Widevine keys for some songs and when the Widevine keys are present the license serve doesn't return the license server.

**Comment by iwlbvk2489** [comment]
So is there a way for me to download lossless using gamdl or do I have to use the bot bit by bit?
