### ISSUE TITLE
More descriptive logging 

### ISSUE THREAD

**Issue by christopher-chandler** [glomatico/gamdl#141]
Please include in the readme that downloads could fail due to `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
`. It took me forever to figure this out.

**Comment by mcosti** [comment]
Would be a lot more constructive if you yourself would share your findings

**Comment by christopher-chandler** [comment]
@zachabobo did this happen to you?
