### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects

### ISSUE THREAD

**Issue by kdj0692** [glomatico/gamdl#147]
PS D:\gamdl-2.3.5> pip install gamdl
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\certifi-2024.8.30-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\charset_normalizer-3.3.2-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\idna-3.9-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\mutagen-1.47.0-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\pillow-10.4.0-py3.13-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\pycryptodomex-3.20.0-py3.13-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\requests-2.32.3-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\urllib3-2.2.3-py3.13.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting gamdl
  Using cached gamdl-2.3.5-py3-none-any.whl.metadata (12 kB)
Collecting ciso8601 (from gamdl)
  Using cached ciso8601-2.3.1.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from gamdl)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting inquirerpy (from gamdl)
  Using cached InquirerPy-0.3.4-py3-none-any.whl.metadata (8.1 kB)
Collecting m3u8 (from gamdl)
  Using cached m3u8-6.0.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: pillow in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\pillow-10.4.0-py3.13-win-amd64.egg (from gamdl) (10.4.0)
Collecting pywidevine (from gamdl)
  Using cached pywidevine-1.8.0-py3-none-any.whl.metadata (9.1 kB)
Collecting pyyaml (from gamdl)
  Using cached PyYAML-6.0.2-cp313-cp313-win_amd64.whl.metadata (2.1 kB)
Collecting yt-dlp (from gamdl)
  Using cached yt_dlp-2024.10.22-py3-none-any.whl.metadata (171 kB)
Collecting colorama (from click->gamdl)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting pfzy<0.4.0,>=0.3.1 (from inquirerpy->gamdl)
  Using cached pfzy-0.3.4-py3-none-any.whl.metadata (4.9 kB)
Collecting prompt-toolkit<4.0.0,>=3.0.1 (from inquirerpy->gamdl)
  Using cached prompt_toolkit-3.0.48-py3-none-any.whl.metadata (6.4 kB)
Collecting Unidecode<2.0.0,>=1.3.7 (from pywidevine->gamdl)
  Using cached Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting protobuf<5.0.0,>=4.25.1 (from pywidevine->gamdl)
  Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Collecting pycryptodome<4.0.0,>=3.19.0 (from pywidevine->gamdl)
  Using cached pycryptodome-3.21.0-cp36-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting pymp4<2.0.0,>=1.4.0 (from pywidevine->gamdl)
  Using cached pymp4-1.4.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\requests-2.32.3-py3.13.egg (from pywidevine->gamdl) (2.32.3)
Collecting brotli (from yt-dlp->gamdl)
  Using cached Brotli-1.1.0-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: certifi in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\certifi-2024.8.30-py3.13.egg (from yt-dlp->gamdl) (2024.8.30)
Requirement already satisfied: mutagen in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\mutagen-1.47.0-py3.13.egg (from yt-dlp->gamdl) (1.47.0)
Requirement already satisfied: pycryptodomex in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\pycryptodomex-3.20.0-py3.13-win-amd64.egg (from yt-dlp->gamdl) (3.20.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\urllib3-2.2.3-py3.13.egg (from yt-dlp->gamdl) (2.2.3)
Collecting websockets>=13.0 (from yt-dlp->gamdl)
  Using cached websockets-13.1-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Collecting wcwidth (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy->gamdl)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting construct==2.8.8 (from pymp4<2.0.0,>=1.4.0->pywidevine->gamdl)
  Using cached construct-2.8.8-py2.py3-none-any.whl
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\charset_normalizer-3.3.2-py3.13.egg (from requests<3.0.0,>=2.31.0->pywidevine->gamdl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kdj06\appdata\local\programs\python\python313\lib\site-packages\idna-3.9-py3.13.egg (from requests<3.0.0,>=2.31.0->pywidevine->gamdl) (3.9)
Using cached gamdl-2.3.5-py3-none-any.whl (32 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached InquirerPy-0.3.4-py3-none-any.whl (67 kB)
Using cached m3u8-6.0.0-py3-none-any.whl (24 kB)
Using cached pywidevine-1.8.0-py3-none-any.whl (70 kB)
Using cached PyYAML-6.0.2-cp313-cp313-win_amd64.whl (156 kB)
Using cached yt_dlp-2024.10.22-py3-none-any.whl (3.2 MB)
Using cached pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Using cached prompt_toolkit-3.0.48-py3-none-any.whl (386 kB)
Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl (413 kB)
Using cached pycryptodome-3.21.0-cp36-abi3-win_amd64.whl (1.8 MB)
Using cached pymp4-1.4.0-py3-none-any.whl (14 kB)
Using cached Unidecode-1.3.8-py3-none-any.whl (235 kB)
Using cached websockets-13.1-cp313-cp313-win_amd64.whl (159 kB)
Using cached Brotli-1.1.0-cp313-cp313-win_amd64.whl (358 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: ciso8601
  Building wheel for ciso8601 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ciso8601 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Users\kdj06\AppData\Local\Temp\pip-build-env-b6yp4gmw\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\kdj06\AppData\Local\Temp\pip-build-env-b6yp4gmw\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\ciso8601
      copying ciso8601\__init__.pyi -> build\lib.win-amd64-cpython-313\ciso8601
      copying ciso8601\py.typed -> build\lib.win-amd64-cpython-313\ciso8601
      running build_ext
      building 'ciso8601' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ciso8601
Failed to build ciso8601
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ciso8601)
PS D:\gamdl-2.3.5>

**Comment by sarvottam99** [comment]
error is in front of your eyes-
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
solution - https://learn.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-14-0-or-greater-is-requir

**Comment by glomatico** [comment]
Should be fixed on the latest version.
