### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by Pedro-Montanari** [glomatico/gamdl#153]
Hello,

I just came acrosss gamdl as I am looking for a way to export my Apple Music library (mainly, my playlists) to a .csv file - basically what services like Tune My Music do, but free. Is it possible to do this with gamdl?

Edit: Tune My Music's free plan has a limit of 500 songs to operate on, while only one of my playlists has more than 600, that's why I was looking for alternatives.

This does not seem to be the scope of gamdl, but I thought to ask if it is possible anyway. 

If not, if it fits the scope of the project I'd leave as a suggestion.

Thanks!

**Comment by youngoris** [comment]
you may try this website [Playlists.cloud](https://playlists.cloud)

**Comment by Pedro-Montanari** [comment]
Okay, that was exactly what I was looking for. Thank you so much!!
