### ISSUE TITLE
Apple Music Playlist 100 Song Limit

### ISSUE THREAD

**Issue by dolesonrobert** [glomatico/gamdl#18]
I have an Apple Music playlist with 5000 songs but gamdl only downloads the first 100.

**Comment by robertdoleson** [comment]
https://github.com/Shubhamrawat5/apple-playlist-downloader/issues/19#issuecomment-1164341252

Seems to be a similar issue related to the beta.apple.music.com scrapping and was worked around.

**Comment by robertdoleson** [comment]
Apple Music docs point to using this api "https://api.music.apple.com/v1/me/library/playlists/{id}" instead of "https://api.music.apple.com/v1/catalog/{storefront}/playlists/{id}"

I haven't been able to get a valid json from that API though.

**Comment by fernvenue** [comment]
Any updates about this issue?

**Comment by florisdipt** [comment]
I just opened a pull request for this https://github.com/glomatico/gamdl/pull/76



> Apple Music docs point to using this api "[https://api.music.apple.com/v1/me/library/playlists/{id}](https://api.music.apple.com/v1/me/library/playlists/%7Bid%7D)" instead of "[https://api.music.apple.com/v1/catalog/{storefront}/playlists/{id}](https://api.music.apple.com/v1/catalog/%7Bstorefront%7D/playlists/%7Bid%7D)"
> 
> I haven't been able to get a valid json from that API though. Seems to be some sort of difference between a Catalog Playlist and a Library Playlist. https://developer.apple.com/documentation/applemusicapi/get_a_catalog_playlist https://developer.apple.com/documentation/applemusicapi/get_a_library_playlist
Just read this after I've already submitted my PR, knowing apple I was assuming there would be do public documentation :cold_face:

Still managed to do it via reverse engineering the API requests I saw my browser send.

**Comment by fernvenue** [comment]
Sooo good to see, hope this feature can be released soon :)
