### ISSUE TITLE
issue - Songs are double-lengthed while videos are fine.

### ISSUE THREAD

**Issue by mosaicbrokenhearts** [glomatico/gamdl#2]
Hi,

I'm just using your scripts for downloading when all videos are fine which I really appreciate. However, when downloading songs, they are all double-lenghted, starting to play all over again when it ends the first time. I guess something wrong when combining the parts?

Thanks :)

**Comment by glomatico** [comment]
Hi. Could you provide a long to your song?

**Comment by mosaicbrokenhearts** [comment]
> Hi. Could you provide the link to your song?

Yeah! I've tried a few & I'll put them here.

https://music.apple.com/us/album/anti-hero-illenium-remix/1655024524?i=1655024534
https://music.apple.com/us/album/voyager/1549187971?i=1549188595
https://music.apple.com/us/album/only-the-young-featured-in-miss-americana/1496696596?i=1496696600

No sure if it's wrong with the remux, cause when downloading, the estimated size of the song is already doubled compared to the original.

ps:) Would this also be able to dl the posts and music movies? I assume the decrypt should be similar, despite that the urls are a bit different. Thanks!!!

**Comment by glomatico** [comment]
I haven't been able to replicate your issue. All songs have downloaded properly.

As for music movies, they are not playable on the web player, so it's not possible to download them.

**Comment by mosaicbrokenhearts** [comment]
Ah I just reinstalled the whole script along with mp4box and mp4decrypt and songs dl are back to normal.

Thanks again!!
