### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by steamgirl2020** [glomatico/gamdl#20]
Download complete, it prompts an error, does it not support the jp area?

gamdl -e https://music.apple.com/jp/music-video/28-reasons/1648400215
Downloading "28 Reasons" (track 1/1 from URL 1/1)
Failed to download "28 Reasons" (track 1/1 from URL 1/1)
Traceback (most recent call last):
  File "C:\Python398\lib\site-packages\gamdl\__init__.py", line 145, in main
    tags = dl.get_tags_music_video(track['attributes']['url'].split('/')[-1])
  File "C:\Python398\lib\site-packages\gamdl\gamdl.py", line 276, in get_tags_music_video
    metadata = requests.get(f'https://itunes.apple.com/lookup?id={track_id}&entity=album&limit=200&country={self.country}&lang=en_US').json()['results']
KeyError: 'results'
Done (1 error(s))

**Comment by glomatico** [comment]
Should be fixed in the new release.
