### ISSUE TITLE
android question

### ISSUE THREAD

**Issue by ozzywrld** [glomatico/gamdl#21]
can this run entirely on android? if so how, the readme doesn't provide me enough info and i don't know how to use python but will probably only use this once. thanks

**Comment by spacex97** [comment]
how to get mp4box for termux rest all i have done

**Comment by itsamgbaba** [comment]
> how to get mp4box for termux rest all i have done
i also wanted to use it 
but no experience .
help me ?

**Comment by ohmyx0y** [comment]
can someone Send me the .wvd i NEED .WVD MY PHONE IS NOT ROOTED

**Comment by p0santuary** [comment]
> can someone Send me the .wvd i NEED .WVD MY PHONE IS NOT ROOTED

have you got one ? @ohmyx0y

**Comment by itsamgbaba** [comment]
no

________________________________
