### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by steamgirl2020** [glomatico/gamdl#22]
Got some errors, please help to have a look, thanks

gamdl -e https://music.apple.com/jp/music-video/864844093
* Failed to check URL 1.
Traceback (most recent call last):
  File "C:\Python398\lib\site-packages\gamdl\__init__.py", line 122, in main
    download_queue.append(dl.get_download_queue(url.strip()))
  File "C:\Python398\lib\site-packages\gamdl\gamdl.py", line 67, in get_download_queue
    response = self.session.get(f'https://amp-api.music.apple.com/v1/catalog/{self.country}/?ids[songs]={product_id}&ids[albums]={product_id}&ids[playlists]={product_id}&ids[music-videos]={product_id}').json()['data'][0]
IndexError: list index out of range
Done (1 error(s))

**Comment by glomatico** [comment]
This happens when the link is not available to download.
