### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by a1waysbeta** [glomatico/gamdl#26]
Downloading "难念的经" (track 1/1 from URL 1/1)
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))
This error message is too little, I don't know where to find the reason.
Please can you help me?

**Comment by a1waysbeta** [comment]
The exported cookies use the default format of the plug-in. I also tried to export other formats, but nothing changed. Every step is done.

**Comment by a1waysbeta** [comment]
I see issue 4, does this require a paid account with a subscription to work? I'm just logged in but not subscribed, so I get an error downloading?

**Comment by glomatico** [comment]
Yes, it requires a subscription.

**Comment by a1waysbeta** [comment]
I subscribed to apple music, and re-exported cookies, but the download was difficult to succeed, and an error was thrown at any time. Is there anything else that needs special attention?
PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/1072048491?i=1072048505
Downloading "难念的经" (track 1/1 from URL 1/1)
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
[download]  86.7% of ~   9.53MiB at  264.14KiB/s ETA 00:09 (frag 26/30)
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))
