### ISSUE TITLE
is this lossy conversion?

### ISSUE THREAD

**Issue by Rainrainraind** [glomatico/gamdl#33]
anyone know how Glomatico's ✨ Apple Music ✨ Downloader works? so far I have learned that it download the fragment and decrypt it, but does decrypting the file but does it convert the file to m4a afterwards? since that would be a lossy to lossy converting which will lower the music quality, I have tried downloading the same link of a song from there and compared it with a itune matched song, the audio stream are different. So it would be nice if someone could explain to me how it works and why the differences in audio stream.

**Comment by Rafawell** [comment]
flac? 48/96/192 Hi-Res???? 🤔

**Comment by futaride** [comment]
Flac uses a different DRM! There is no public method for ripping flac.
