### ISSUE TITLE
在执行代码pywidevine create-device -t ANDROID -l 3 -k private_key.pem -c client_id.bin -o .时发生错误

### ISSUE THREAD

**Issue by matnothingok09** [glomatico/gamdl#38]
显示
INFO:root:pywidevine version 1.5.3 Copyright (c) 2022-2023 rlaphoenix
INFO:root:https://github.com/rlaphoenix/pywidevine
Usage: pywidevine create-device [OPTIONS]
Try 'pywidevine create-device --help' for help.

Error: key: Not a path to a file, or it doesn't exist.
但我已将其添加至PATH

**Comment by glomatico** [comment]
Not related to gamdl.
