### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [glomatico/gamdl#4]
HEY DUDE...CONGRATULATIONSSSSSSSSS FOR THIS AMAZING PROJECT...BUT PLEASE CAN YOU HELP ME HOW TO RUN IT?AND TELL ME PLEASE I NEED ITUNES PREMIUM ACOUNT?

**Comment by glomatico** [comment]
Hello! Instructions are in [README.md](https://github.com/glomatico/gamdl/blob/main/README.md). You need a Apple Music subscriptium to use it.
