### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by sureshfizzy** [glomatico/gamdl#40]
Whenever i run the command i get this error

 gamdl "https://music.apple.com/us/album/whenever-you-need-somebody-2022-remaster/1626265761"
[INFO     11:24:31] Downloading "Never Gonna Give You Up (2022 - Remaster)" (track 1/10 from URL 1/1)
[ERROR    11:24:32] Failed to download "Never Gonna Give You Up (2022 - Remaster)" (track 1/10 from URL 1/1)
[INFO     11:24:32] Downloading "Whenever You Need Somebody (2022 - Remaster)" (track 2/10 from URL 1/1)
[ERROR    11:24:33] Failed to download "Whenever You Need Somebody (2022 - Remaster)" (track 2/10 from URL 1/1)
[INFO     11:24:33] Downloading "Together Forever (2022 - Remaster)" (track 3/10 from URL 1/1)
[ERROR    11:24:33] Failed to download "Together Forever (2022 - Remaster)" (track 3/10 from URL 1/1)
[INFO     11:24:33] Downloading "It Would Take a Strong Strong Man (2022 - Remaster)" (track 4/10 from URL 1/1)
[ERROR    11:24:34] Failed to download "It Would Take a Strong Strong Man (2022 - Remaster)" (track 4/10 from URL 1/1)
[INFO     11:24:34] Downloading "The Love Has Gone (2022 - Remaster)" (track 5/10 from URL 1/1)
[ERROR    11:24:35] Failed to download "The Love Has Gone (2022 - Remaster)" (track 5/10 from URL 1/1)
[INFO     11:24:35] Downloading "Don't Say Goodbye (2022 - Remaster)" (track 6/10 from URL 1/1)
[ERROR    11:24:35] Failed to download "Don't Say Goodbye (2022 - Remaster)" (track 6/10 from URL 1/1)
[INFO     11:24:35] Downloading "Slipping Away (2022 - Remaster)" (track 7/10 from URL 1/1)
[ERROR    11:24:36] Failed to download "Slipping Away (2022 - Remaster)" (track 7/10 from URL 1/1)
[INFO     11:24:36] Downloading "No More Looking for Love (2022 - Remaster)" (track 8/10 from URL 1/1)
[ERROR    11:24:36] Failed to download "No More Looking for Love (2022 - Remaster)" (track 8/10 from URL 1/1)
[INFO     11:24:36] Downloading "You Move Me (2022 - Remaster)" (track 9/10 from URL 1/1)
[ERROR    11:24:37] Failed to download "You Move Me (2022 - Remaster)" (track 9/10 from URL 1/1)
[INFO     11:24:37] Downloading "When I Fall in Love (2022 - Remaster)" (track 10/10 from URL 1/1)
[ERROR    11:24:37] Failed to download "When I Fall in Love (2022 - Remaster)" (track 10/10 from URL 1/1)
[INFO     11:24:37] Done (10 error(s))

**Comment by glomatico** [comment]
Please provide output when adding `--print-exceptiond` to your command

**Comment by sureshfizzy** [comment]
> 

gamdl "https://music.apple.com/us/album/never-gonna-give-you-up-2022-remaster/1626265761?i=1626265765" --print-exceptions
[INFO     13:24:36] Downloading "Never Gonna Give You Up (2022 - Remaster)" (track 1/1 from URL 1/1)
[ERROR    13:24:37] Failed to download "Never Gonna Give You Up (2022
- Remaster)" (track 1/1 from URL 1/1)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gamdl/cli.py", line 378, in main
    decryption_key = dl.get_decryption_key_song(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gamdl/dl.py", line 330, in get_decryption_key_song
    license_b64 = self.get_license_b64(challenge, track_uri, track_id)  File "/home/ubuntu/.local/lib/python3.10/site-packages/gamdl/dl.py", line 292, in get_license_b64
    return self.session.post(
KeyError: 'license'
[INFO     13:24:37] Done (1 error(s))

**Comment by glomatico** [comment]
You didn't provided a valid .wvd file

**Comment by sureshfizzy** [comment]
> You didn't provided a valid .wvd file

Should I dump again and run the widevine script ?

**Comment by glomatico** [comment]
I think so. If it doesn't again try dumping from another decide

**Comment by sureshfizzy** [comment]
Thanks for your time, re-dumping the widewine fixed the issue.

**Comment by Droidman007** [comment]
Hey can you please give me wvd file
