### ISSUE TITLE
Urls failing to check/not downloadable using current settings

### ISSUE THREAD

**Issue by ssjbrap** [glomatico/gamdl#43]
Is there a way to download videos that don't have "music-video" in the url? When I try to it says the url fails to check or that it's not downloadable using current settings. I don't know if there's a way around this. Here's a couple examples of what I'm talking about

https://music.apple.com/us/post/1706425487
https://music.apple.com/us/music-movie/taylor-swift-lyrics-that-hook-you/1480458035

They both have videos in the link so I'm not sure why they don't download.

**Comment by glomatico** [comment]
Music movies are not streamable on web and post videos are DRM free.
