### ISSUE TITLE
[Request] Enhanced LRC, with word by word synced lyrics.

### ISSUE THREAD

**Issue by SMNFXCN** [glomatico/gamdl#65]
Some tracks on AM have timed lyrics that sync up with each word, with some emphasis on some words.
Is it possible to rip these, and have them in .LRC?
For reference, [this](https://en.wikipedia.org/wiki/LRC_(file_format)#A2_extension:_word_time_tag) is what I'm referring to, when I mean Enhanced LRC.

**Comment by glomatico** [comment]
Do you know any players that support this enhanced LRC?

**Comment by SimonFoxcoon** [comment]
Personally, no, as I haven't been able to find any enhanced LRCs out there. Foobar2000 with a component might be able to. I think that Wikipedia page shows basic LRC support, instead.

**Comment by a1waysbeta** [comment]
foobar2000 + ESLYric。https://github.com/ESLyric/release/releases/tag/0.5.4.1025
