### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by Abhi5033** [glomatico/gamdl#71]
![image](https://github.com/glomatico/gamdl/assets/118114270/c2c56a61-77ba-4ea8-965c-ad84d5c0db67)

I extracted device.wvd and did all the process correctly

**Comment by glomatico** [comment]
You're using an old FFmpeg version or an incompatible build. Try using a different one.
I recommend using this FFmpeg build with gamdl on Windows: https://github.com/AnimMouse/ffmpeg-stable-autobuild/releases

**Comment by Abhi5033** [comment]
Thanks I updated to latest ffmpeg and now songs are downloading fine.
I tried  music video. Video downloaded and decrypted properly but audio isn't.
Audio is like stucking.
I tried this one https://music.apple.com/in/music-video/pranama-from-darling/895357991
