### ISSUE TITLE
The source of audio files

### ISSUE THREAD

**Issue by dimasix9** [glomatico/gamdl#77]
@glomatico hi, lately I was wondering what is the source of audio files you implemented. Is this AM or YouTube? I’m asking about this because in readme you mentioned that yt-dlp used for downloading. So does your app find the similar song on YT or get it directly from AM/iTunes? 
Thanks in advance.

**Comment by Silergo** [comment]
From AM itself. yt-dlp is just a module that is used for downloading. It can be applied to any streaming source, not just Youtube. If you don't like it, you can use N_m3u8DL-RE, which does the same thing.
