### ISSUE TITLE
Downlod Failed with 1 Error

### ISSUE THREAD

**Issue by 2mnml** [glomatico/gamdl#80]
gamdl "https://music.apple.com/us/album/never-gonna-give-you-up-2022-remaster/1626265761?i=1626265765" --print-exceptions

[ERROR    18:13:28] (URL 1/1) Failed to check "https://music.apple.com/us/album/never-gonna-give-you-up-2022-remaster/1626265761?i=1626265765"
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/cli.py", line 361, in main
    download_queue.append(downloader.get_download_queue(url))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/downloader.py", line 193, in get_download_queue
    download_queue.append(self.get_song(catalog_id))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/downloader.py", line 132, in get_song
    raise Exception(f"Failed to get song: {song_response.text}")
Exception: Failed to get song: {"errors":[{"id":"GCSQ65L3URYBWKH554DNIUNPII","title":"Resource Not Found","detail":"Resource with requested id was not found","status":"404","code":"40400"}]}
[INFO     18:13:28] Done (1 error(s))

This happens no matter what i try to download.

**Comment by ajitid** [comment]
It's song ID has been changed, try this:

```
gamdl "music.apple.com/us/album/never-gonna-give-you-up-2022-remaster/1624945511?i=1624945512" --print-exceptions
```
