### ISSUE TITLE
Problems with incomplete file names after downloading

### ISSUE THREAD

**Issue by bdim404** [glomatico/gamdl#83]
Hello, I've been working on secondary development through your project recently, and I've noticed that m4a files after downloading through gamdl are truncated if the music name is too long.

The music I tested is:
https://music.apple.com/us/album/1-800-273-8255-feat-alessia-cara-khalid/1456232697?i=1456232983
After downloading it is stored as . /Apple Music/Logic/Everybody (Deluxe Edition)/10 1-800-273-8255 (feat. Alessia Car.m4a

So when I get that song title from Apple Music, it doesn't look up from the file I've already downloaded, because its correct song title is: 1-800-273-8255 (feat. Alessia Cara & Khalid).m4a

```
# your file name
file_path = "./Apple Music/Logic/Everybody (Deluxe Edition)/10 1-800-273-8255 (feat. Alessia Car.m4a"

# the right file name
file_path = "/Apple Music/Logic/Everybody (Deluxe Edition)/1-800-273-8255 (feat. Alessia Cara & Khalid).m4a"
```

**Comment by fernvenue** [comment]
Can be reproduced:

![image](https://github.com/glomatico/gamdl/assets/84565547/f0685ef1-1101-4e42-adfe-bb1a925400ec)

Seems both the folder name and file name are truncated.

**Comment by glomatico** [comment]
That's the expected behavior if you don't change the `truncate` configuration. Take a look on the README file for more details.

**Comment by fernvenue** [comment]
Ah, thanks for your reply :)

**Comment by bdim404** [comment]
> That's the expected behavior if you don't change the `truncate` configuration. Take a look on the README file for more details.

Thx！
