### ISSUE TITLE
Music Videos Do Not Gets Download (Not All)

### ISSUE THREAD

**Issue by Rajeshsahoo12** [glomatico/gamdl#88]
Hi Dev,

Have recently started using to download music tracks & music videos from apple music. And I have setup according to the instructions in repo.

But I faced issue related to music videos not getting downloaded. It does not happen with all music videos. For the information I have set `TRUE to "ask_video_format"` parameter in config.json.

`No errors at all music videos :-`

gamdl **https://music.apple.com/in/music-video/no-angels/1735396016**

![image](https://github.com/glomatico/gamdl/assets/54216637/b670a72a-31a4-4ddd-8290-80054e9744a3)

`Errors in music videos download :-`

![image](https://github.com/glomatico/gamdl/assets/54216637/49ec2b5e-eff2-4008-9474-58cd1f9d22e1)

https://music.apple.com/in/music-video/rich-baby-daddy-feat-sexxy-red-sza/1731033374

https://music.apple.com/in/music-video/spin-bout-u/1674251945

https://music.apple.com/in/music-video/you-broke-my-heart/1722308116

https://music.apple.com/in/music-video/polar-opposites/1719163980

https://music.apple.com/in/music-video/first-person-shooter-feat-j-cole/1717084940

Thanks

**Comment by glomatico** [comment]
Please send the output of the command with `--print-exceptions` added in the command.

**Comment by Rajeshsahoo12** [comment]
> --print-exceptions

Thanks dev for quick response. As u said here I have attached error SS for tried command with url.

`gamdl https://music.apple.com/in/music-video/rich-baby-daddy-feat-sexxy-red-sza/1731033374 --print-exceptions`



![image](https://github.com/glomatico/gamdl/assets/54216637/c8910956-42d4-4ea1-9d1d-3ab75671c27c)


Thanks

**Comment by glomatico** [comment]
Check your cookies.

**Comment by Rajeshsahoo12** [comment]
> Check your cookies.

I got cookies using this tool mentioned in repo. I am using trial account. Is this a problem..?

Do I need to get fresh cookies..?

**Comment by Rajeshsahoo12** [comment]
> gamdl https://music.apple.com/in/music-video/rich-baby-daddy-feat-sexxy-red-sza/1731033374

I have generated fresh cookies & tried again. But it failed. 

Then I changed these param in config file to `true` `"prefer_hevc"`, `"print_exceptions"`

And wow the videos which were throwing errors earlier. Now, this was the result.

![image](https://github.com/glomatico/gamdl/assets/54216637/98aa320f-f8b0-4d7b-9096-dc5b492c8922)



Thanks
