### ISSUE TITLE
aria2 failed

### ISSUE THREAD

**Issue by evafans** [glomatico/gamdl#9]
regular download is ok.
but aira2 gives errors:
[DL:0B][#56ca3e 0B/0B][#e3a4e6 0B/0B][#8b8bb4 0B/0B][#12cedb 0B/0B][#695df7 0B/0B](+11)
01/27 23:45:05 [ERROR] CUID#12 - Download aborted. URI=https://mvod.itunes.apple.com/itunes-assets/HLSVideo124/v4/50/fc/7e/50fc7e99-9886-b2d8-5afb-13d93e415288/P231676897_A1356863152_MV_en_audio_gr256-5.mp4
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://mvod.itunes.apple.com/itunes-assets/HLSVideo124/v4/50/fc/7e/50fc7e99-9886-b2d8-5afb-13d93e415288/P231676897_A1356863152_MV_en_audio_gr256-5.mp4
  -> [AbstractCommand.cc:792] errorCode=19 CUID#12 - Name resolution for mvod.itunes.apple.com failed:Timeout while contacting DNS servers

**Comment by glomatico** [comment]
That's a issue with your internet.
