### ISSUE TITLE
cookies file not found at "cookies.txt"

### ISSUE THREAD

**Issue by cakroqi223** [glomatico/gamdl#90]
i have to import file cookies with same rule, and i place the .txt file in C:User/name/AppData/Roaming/Phyton/Phyton 312/site-packages/gamdl but if i run the gamdl the notification appears

is there something wrong with my method?

**Comment by glomatico** [comment]
You did not place the file on the current directory as the script expects. Either do that or manually set the path using the config file or the command line arguments.
