### ISSUE TITLE
Variation In Behaviour

### ISSUE THREAD

**Issue by Rajeshsahoo12** [glomatico/gamdl#93]
Hi Dev,

I am using latest build which of `gamdl 2.1.1` , but I have experienced a behavior which I am mentioning here. Using `download_mode = nm3u8dlre` & `remux_mode = ffmpeg`

Behavior with this track `https://music.apple.com/in/album/bandara/316923874?i=316923878`

When I use this command `gamdl "https://music.apple.com/in/album/bandara/316923874?i=316923878" ` with --codec-song ask flag. Below is the output.

![image](https://github.com/glomatico/gamdl/assets/54216637/928f1ae7-8717-4b56-a7c8-8aa9c3174737)

When I use this command `gamdl "https://music.apple.com/in/album/bandara/316923874?i=316923878" ` .
Below is the output.

![image](https://github.com/glomatico/gamdl/assets/54216637/01bb60ed-10c3-4e99-9dc5-563f516ded03)

Behavior with this track `https://music.apple.com/in/album/ishq-mitaye/1738489671?i=1738489822`

When I use this command `gamdl "https://music.apple.com/in/album/ishq-mitaye/1738489671?i=1738489822" ` with --codec-song ask flag. Below is the output. Which is working fine. As it is asking for codec no to be feed from user end.

![image](https://github.com/glomatico/gamdl/assets/54216637/5a1ccd95-2f22-4d5b-affc-ad7663dcfd15)

Issue here is for one track --codec-song ask is working fine. But not for other.

Thanks

**Comment by glomatico** [comment]
These tracks cannot be downloaded on non-legacy codecs. As I said on the README, non-legacy support is not guaranteed.
