### ISSUE TITLE
What Video Qualities Available..?

### ISSUE THREAD

**Issue by Rajeshsahoo12** [glomatico/gamdl#94]
Hi Dev,

I am using latest build which of `gamdl 2.1.1`, but when I am using `--codec-song ask` with music videos url. It is not asking for user input   for which quality & audio file id. The program directly downloads the video. Here below is the SS of the same.

![image](https://github.com/glomatico/gamdl/assets/54216637/73a6d527-ff76-45a0-a6db-a4c65d2cdabe)

Thanks

**Comment by glomatico** [comment]
--codec-**music-video-ask**

**Comment by Rajeshsahoo12** [comment]
> --codec-**music-video ask**

Thanks dev

![image](https://github.com/glomatico/gamdl/assets/54216637/ee745624-b176-4313-9f55-593f41811196)
