### ISSUE TITLE
Song Does Not Contain Widevine Drm, Skipping (Warning In Terminal) 

### ISSUE THREAD

**Issue by Rajeshsahoo12** [glomatico/gamdl#95]
Hi Dev,

These tracks are available in  `DOLBY ATMOS` but when program tries to download them. I get this `WARNING` info in terminal.
|
|
|
|
[WARNING  05:36:30] (Track 4/12 from URL 1/1) Song does not contain Widevine DRM, skipping
[WARNING  05:36:34] (Track 9/12 from URL 1/1) Song does not contain Widevine DRM, skipping
[WARNING  05:36:35] (Track 11/12 from URL 1/1) Song does not contain Widevine DRM, skipping
[WARNING  05:36:36] (Track 12/12 from URL 1/1) Song does not contain Widevine DRM, skipping

|
|
|
|
**https://music.apple.com/kr/album/numb/1698482681?i=1698482807**

![image](https://github.com/glomatico/gamdl/assets/54216637/8702d6fa-851d-4815-8dd7-69b983653207)
|
|
|
|
**https://music.apple.com/kr/album/stay-feat-tablo/1698482681?i=1698482813**

![image](https://github.com/glomatico/gamdl/assets/54216637/35d15ed5-8be7-469d-91ae-6638efd50f9b)
|
|
|
|
**https://music.apple.com/kr/album/%EA%B7%B8%EB%95%90-%EB%82%B4%EA%B0%80/1698482681?i=1698482815**

![image](https://github.com/glomatico/gamdl/assets/54216637/c3c40d28-e9b7-44ac-8daf-6dbfa16b29c5)
|
|
|
|
**https://music.apple.com/kr/album/%EB%8B%A4%EC%9D%8C-%EC%83%9D/1698482681?i=1698482816**

![image](https://github.com/glomatico/gamdl/assets/54216637/9dae6ea2-99a5-419d-a9b3-fc451160455c)

Thanks

**Comment by glomatico** [comment]
Update to the last version and try again.
