### ISSUE TITLE
Cookies.txt file not being found 

### ISSUE THREAD

**Issue by rkuli** [glomatico/gamdl#99]
![IMG_5699](https://github.com/glomatico/gamdl/assets/126831718/a8b9567c-afe3-4491-9906-3edb960e5fe5)
Keeps saying the cookies.txt isn’t there and I’ve placed it in every folder labeled gamdl. Is there a specific folder or place where I’m supposed to place it that I don’t know of?

**Comment by jhonata-ms** [comment]
The same thing happens when a run on android termux terminal.

**Comment by glomatico** [comment]
You have not place the cookies on the current directory. Do it like so or specify the location using the cookies path option.
